name: my_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  supabase: ^2.8.0
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0
  logging: ^1.2.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0