name: Sync to Google Drive (multi-folders)

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      # Додай/зміни перелік папок тут (через пробіл)
      SYNC_DIRS: "landing lib web supabase android ios"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: curl -fsSL https://rclone.org/install.sh | sudo bash

      - name: Write service account key
        run: echo "${{ secrets.GDRIVE_SA_JSON }}" > sa.json

      - name: Rclone config
        run: |
          cat > rclone.conf <<EOF
          [gd]
          type = drive
          scope = drive
          service_account_file = ${GITHUB_WORKSPACE}/sa.json
          root_folder_id = ${{ secrets.GDRIVE_FOLDER_ID }}
          EOF

      - name: Sync listed folders
        shell: bash
        run: |
          set -e
          IFS=' ' read -r -a DIRS <<< "${SYNC_DIRS}"
          for d in "${DIRS[@]}"; do
            if [ -d "$d" ]; then
              echo ">> Sync $d -> gd:$d"
              rclone sync "$d" "gd:$d" \
                --config rclone.conf \
                --fast-list --transfers 8 --checkers 16 \
                --exclude ".DS_Store" \
                --exclude "**/node_modules/**" \
                --exclude "**/build/**" \
                --exclude "**/dist/**" \
                --exclude "**/.gradle/**" \
                --exclude "**/.cxx/**" \
                --exclude "**/Pods/**" \
                --exclude "**/DerivedData/**" \
                --exclude "**/*.log" \
                --exclude "**/*.apk" \
                --exclude "**/*.aab" \
                --exclude "**/*.ipa" \
                --delete-excluded
            else
              echo "::notice::Skip $d (not found)"
            fi
          done
